/*
 * dom2views.idl
 *
 * DOM Level 2 Views IDL definitions, rewritten in Web IDL.
 *
 * Original OMG IDL:
 *
 *   http://www.w3.org/TR/2000/REC-DOM-Level-2-Views-20001113/views.idl
 */

module views {

  typedef dom::Document Document;

  // Introduced in DOM Level 2:
  [PrototypeRoot]
  interface AbstractView {
    readonly attribute DocumentView     document;
  };

  // Introduced in DOM Level 2:
  interface DocumentView {
    readonly attribute AbstractView     defaultView;
  };

  Document implements DocumentView;
};
