/*
 * dom2css.idl
 *
 * DOM Level 2 CSS IDL definitions, rewritten in Web IDL.
 *
 * Original OMG IDL:
 *
 *   http://www.w3.org/TR/2000/REC-DOM-Level-2-Style-20001113/css.idl
 */

module css {

  typedef dom::Document Document;
  typedef dom::Element Element;
  typedef dom::DOMImplementation DOMImplementation;
  typedef dom::DOMException DOMException;
  typedef views::AbstractView AbstractView;

  // Introduced in DOM Level 2:
  interface CSSRuleList {
    readonly attribute unsigned long length;
    getter CSSRule item(in unsigned long index);
  };

  // Introduced in DOM Level 2:
  [PrototypeRoot]
  interface CSSRule {

    // RuleType
    const unsigned short      UNKNOWN_RULE                   = 0;
    const unsigned short      STYLE_RULE                     = 1;
    const unsigned short      CHARSET_RULE                   = 2;
    const unsigned short      IMPORT_RULE                    = 3;
    const unsigned short      MEDIA_RULE                     = 4;
    const unsigned short      FONT_FACE_RULE                 = 5;
    const unsigned short      PAGE_RULE                      = 6;

    readonly attribute unsigned short   type;
             attribute DOMString        cssText setraises(DOMException);

    readonly attribute CSSStyleSheet    parentStyleSheet;
    readonly attribute CSSRule          parentRule;
  };

  // Introduced in DOM Level 2:
  interface CSSStyleRule : CSSRule {
             attribute DOMString        selectorText setraises(DOMException);

    readonly attribute CSSStyleDeclaration  style;
  };

  // Introduced in DOM Level 2:
  interface CSSMediaRule : CSSRule {
    readonly attribute stylesheets::MediaList  media;
    readonly attribute CSSRuleList      cssRules;
    unsigned long      insertRule(in DOMString rule, 
                                  in unsigned long index)
                                        raises(DOMException);
    void               deleteRule(in unsigned long index)
                                        raises(DOMException);
  };

  // Introduced in DOM Level 2:
  interface CSSFontFaceRule : CSSRule {
    readonly attribute CSSStyleDeclaration  style;
  };

  // Introduced in DOM Level 2:
  interface CSSPageRule : CSSRule {
             attribute DOMString        selectorText setraises(DOMException);

    readonly attribute CSSStyleDeclaration  style;
  };

  // Introduced in DOM Level 2:
  interface CSSImportRule : CSSRule {
    readonly attribute DOMString        href;
    readonly attribute stylesheets::MediaList  media;
    readonly attribute CSSStyleSheet    styleSheet;
  };

  // Introduced in DOM Level 2:
  interface CSSCharsetRule : CSSRule {
             attribute DOMString        encoding setraises(DOMException);

  };

  // Introduced in DOM Level 2:
  interface CSSUnknownRule : CSSRule {
  };

  // Introduced in DOM Level 2:
  interface CSSStyleDeclaration {
             attribute DOMString        cssText setraises(DOMException);

    DOMString          getPropertyValue(in DOMString propertyName);
    CSSValue           getPropertyCSSValue(in DOMString propertyName);
    DOMString          removeProperty(in DOMString propertyName)
                                        raises(DOMException);
    DOMString          getPropertyPriority(in DOMString propertyName);
    void               setProperty(in DOMString propertyName, 
                                   in DOMString value, 
                                   in DOMString? priority)
                                        raises(DOMException);
    readonly attribute unsigned long    length;
    getter DOMString item(in unsigned long index);
    readonly attribute CSSRule          parentRule;
  };

  // Introduced in DOM Level 2:
  [PrototypeRoot]
  interface CSSValue {

    // UnitTypes
    const unsigned short      CSS_INHERIT                    = 0;
    const unsigned short      CSS_PRIMITIVE_VALUE            = 1;
    const unsigned short      CSS_VALUE_LIST                 = 2;
    const unsigned short      CSS_CUSTOM                     = 3;

             attribute DOMString        cssText setraises(DOMException);

    readonly attribute unsigned short   cssValueType;
  };

  // Introduced in DOM Level 2:
  interface CSSPrimitiveValue : CSSValue {

    // UnitTypes
    const unsigned short      CSS_UNKNOWN                    = 0;
    const unsigned short      CSS_NUMBER                     = 1;
    const unsigned short      CSS_PERCENTAGE                 = 2;
    const unsigned short      CSS_EMS                        = 3;
    const unsigned short      CSS_EXS                        = 4;
    const unsigned short      CSS_PX                         = 5;
    const unsigned short      CSS_CM                         = 6;
    const unsigned short      CSS_MM                         = 7;
    const unsigned short      CSS_IN                         = 8;
    const unsigned short      CSS_PT                         = 9;
    const unsigned short      CSS_PC                         = 10;
    const unsigned short      CSS_DEG                        = 11;
    const unsigned short      CSS_RAD                        = 12;
    const unsigned short      CSS_GRAD                       = 13;
    const unsigned short      CSS_MS                         = 14;
    const unsigned short      CSS_S                          = 15;
    const unsigned short      CSS_HZ                         = 16;
    const unsigned short      CSS_KHZ                        = 17;
    const unsigned short      CSS_DIMENSION                  = 18;
    const unsigned short      CSS_STRING                     = 19;
    const unsigned short      CSS_URI                        = 20;
    const unsigned short      CSS_IDENT                      = 21;
    const unsigned short      CSS_ATTR                       = 22;
    const unsigned short      CSS_COUNTER                    = 23;
    const unsigned short      CSS_RECT                       = 24;
    const unsigned short      CSS_RGBCOLOR                   = 25;

    readonly attribute unsigned short   primitiveType;
    void               setFloatValue(in unsigned short unitType, 
                                     in float floatValue)
                                        raises(DOMException);
    float              getFloatValue(in unsigned short unitType)
                                        raises(DOMException);
    void               setStringValue(in unsigned short stringType, 
                                      in DOMString stringValue)
                                        raises(DOMException);
    DOMString          getStringValue()
                                        raises(DOMException);
    Counter            getCounterValue()
                                        raises(DOMException);
    Rect               getRectValue()
                                        raises(DOMException);
    RGBColor           getRGBColorValue()
                                        raises(DOMException);
  };

  // Introduced in DOM Level 2:
  interface CSSValueList : CSSValue {
    readonly attribute unsigned long length;
    getter CSSValue item(in unsigned long index);
  };

  // Introduced in DOM Level 2:
  interface RGBColor {
    readonly attribute CSSPrimitiveValue  red;
    readonly attribute CSSPrimitiveValue  green;
    readonly attribute CSSPrimitiveValue  blue;
  };

  // Introduced in DOM Level 2:
  interface Rect {
    readonly attribute CSSPrimitiveValue  top;
    readonly attribute CSSPrimitiveValue  right;
    readonly attribute CSSPrimitiveValue  bottom;
    readonly attribute CSSPrimitiveValue  left;
  };

  // Introduced in DOM Level 2:
  interface Counter {
    readonly attribute DOMString        identifier;
    readonly attribute DOMString        listStyle;
    readonly attribute DOMString        separator;
  };

  // Introduced in DOM Level 2:
  interface ElementCSSInlineStyle {
    readonly attribute CSSStyleDeclaration  style;
  };

  // Introduced in DOM Level 2:
  interface CSS2Properties {
             attribute DOMString        azimuth setraises(DOMException);

             attribute DOMString        background setraises(DOMException);

             attribute DOMString        backgroundAttachment setraises(DOMException);

             attribute DOMString        backgroundColor setraises(DOMException);

             attribute DOMString        backgroundImage setraises(DOMException);

             attribute DOMString        backgroundPosition setraises(DOMException);

             attribute DOMString        backgroundRepeat setraises(DOMException);

             attribute DOMString        border setraises(DOMException);

             attribute DOMString        borderCollapse setraises(DOMException);

             attribute DOMString        borderColor setraises(DOMException);

             attribute DOMString        borderSpacing setraises(DOMException);

             attribute DOMString        borderStyle setraises(DOMException);

             attribute DOMString        borderTop setraises(DOMException);

             attribute DOMString        borderRight setraises(DOMException);

             attribute DOMString        borderBottom setraises(DOMException);

             attribute DOMString        borderLeft setraises(DOMException);

             attribute DOMString        borderTopColor setraises(DOMException);

             attribute DOMString        borderRightColor setraises(DOMException);

             attribute DOMString        borderBottomColor setraises(DOMException);

             attribute DOMString        borderLeftColor setraises(DOMException);

             attribute DOMString        borderTopStyle setraises(DOMException);

             attribute DOMString        borderRightStyle setraises(DOMException);

             attribute DOMString        borderBottomStyle setraises(DOMException);

             attribute DOMString        borderLeftStyle setraises(DOMException);

             attribute DOMString        borderTopWidth setraises(DOMException);

             attribute DOMString        borderRightWidth setraises(DOMException);

             attribute DOMString        borderBottomWidth setraises(DOMException);

             attribute DOMString        borderLeftWidth setraises(DOMException);

             attribute DOMString        borderWidth setraises(DOMException);

             attribute DOMString        bottom setraises(DOMException);

             attribute DOMString        captionSide setraises(DOMException);

             attribute DOMString        clear setraises(DOMException);

             attribute DOMString        clip setraises(DOMException);

             attribute DOMString        color setraises(DOMException);

             attribute DOMString        content setraises(DOMException);

             attribute DOMString        counterIncrement setraises(DOMException);

             attribute DOMString        counterReset setraises(DOMException);

             attribute DOMString        cue setraises(DOMException);

             attribute DOMString        cueAfter setraises(DOMException);

             attribute DOMString        cueBefore setraises(DOMException);

             attribute DOMString        cursor setraises(DOMException);

             attribute DOMString        direction setraises(DOMException);

             attribute DOMString        display setraises(DOMException);

             attribute DOMString        elevation setraises(DOMException);

             attribute DOMString        emptyCells setraises(DOMException);

             attribute DOMString        cssFloat setraises(DOMException);

             attribute DOMString        font setraises(DOMException);

             attribute DOMString        fontFamily setraises(DOMException);

             attribute DOMString        fontSize setraises(DOMException);

             attribute DOMString        fontSizeAdjust setraises(DOMException);

             attribute DOMString        fontStretch setraises(DOMException);

             attribute DOMString        fontStyle setraises(DOMException);

             attribute DOMString        fontVariant setraises(DOMException);

             attribute DOMString        fontWeight setraises(DOMException);

             attribute DOMString        height setraises(DOMException);

             attribute DOMString        left setraises(DOMException);

             attribute DOMString        letterSpacing setraises(DOMException);

             attribute DOMString        lineHeight setraises(DOMException);

             attribute DOMString        listStyle setraises(DOMException);

             attribute DOMString        listStyleImage setraises(DOMException);

             attribute DOMString        listStylePosition setraises(DOMException);

             attribute DOMString        listStyleType setraises(DOMException);

             attribute DOMString        margin setraises(DOMException);

             attribute DOMString        marginTop setraises(DOMException);

             attribute DOMString        marginRight setraises(DOMException);

             attribute DOMString        marginBottom setraises(DOMException);

             attribute DOMString        marginLeft setraises(DOMException);

             attribute DOMString        markerOffset setraises(DOMException);

             attribute DOMString        marks setraises(DOMException);

             attribute DOMString        maxHeight setraises(DOMException);

             attribute DOMString        maxWidth setraises(DOMException);

             attribute DOMString        minHeight setraises(DOMException);

             attribute DOMString        minWidth setraises(DOMException);

             attribute DOMString        orphans setraises(DOMException);

             attribute DOMString        outline setraises(DOMException);

             attribute DOMString        outlineColor setraises(DOMException);

             attribute DOMString        outlineStyle setraises(DOMException);

             attribute DOMString        outlineWidth setraises(DOMException);

             attribute DOMString        overflow setraises(DOMException);

             attribute DOMString        padding setraises(DOMException);

             attribute DOMString        paddingTop setraises(DOMException);

             attribute DOMString        paddingRight setraises(DOMException);

             attribute DOMString        paddingBottom setraises(DOMException);

             attribute DOMString        paddingLeft setraises(DOMException);

             attribute DOMString        page setraises(DOMException);

             attribute DOMString        pageBreakAfter setraises(DOMException);

             attribute DOMString        pageBreakBefore setraises(DOMException);

             attribute DOMString        pageBreakInside setraises(DOMException);

             attribute DOMString        pause setraises(DOMException);

             attribute DOMString        pauseAfter setraises(DOMException);

             attribute DOMString        pauseBefore setraises(DOMException);

             attribute DOMString        pitch setraises(DOMException);

             attribute DOMString        pitchRange setraises(DOMException);

             attribute DOMString        playDuring setraises(DOMException);

             attribute DOMString        position setraises(DOMException);

             attribute DOMString        quotes setraises(DOMException);

             attribute DOMString        richness setraises(DOMException);

             attribute DOMString        right setraises(DOMException);

             attribute DOMString        size setraises(DOMException);

             attribute DOMString        speak setraises(DOMException);

             attribute DOMString        speakHeader setraises(DOMException);

             attribute DOMString        speakNumeral setraises(DOMException);

             attribute DOMString        speakPunctuation setraises(DOMException);

             attribute DOMString        speechRate setraises(DOMException);

             attribute DOMString        stress setraises(DOMException);

             attribute DOMString        tableLayout setraises(DOMException);

             attribute DOMString        textAlign setraises(DOMException);

             attribute DOMString        textDecoration setraises(DOMException);

             attribute DOMString        textIndent setraises(DOMException);

             attribute DOMString        textShadow setraises(DOMException);

             attribute DOMString        textTransform setraises(DOMException);

             attribute DOMString        top setraises(DOMException);

             attribute DOMString        unicodeBidi setraises(DOMException);

             attribute DOMString        verticalAlign setraises(DOMException);

             attribute DOMString        visibility setraises(DOMException);

             attribute DOMString        voiceFamily setraises(DOMException);

             attribute DOMString        volume setraises(DOMException);

             attribute DOMString        whiteSpace setraises(DOMException);

             attribute DOMString        widows setraises(DOMException);

             attribute DOMString        width setraises(DOMException);

             attribute DOMString        wordSpacing setraises(DOMException);

             attribute DOMString        zIndex setraises(DOMException);

  };

  // Introduced in DOM Level 2:
  interface CSSStyleSheet : stylesheets::StyleSheet {
    readonly attribute CSSRule          ownerRule;
    readonly attribute CSSRuleList      cssRules;
    unsigned long      insertRule(in DOMString rule, 
                                  in unsigned long index)
                                        raises(DOMException);
    void               deleteRule(in unsigned long index)
                                        raises(DOMException);
  };

  // Introduced in DOM Level 2:
  interface ViewCSS /*: views::AbstractView*/ {
    CSSStyleDeclaration getComputedStyle(in Element elt, 
                                         in DOMString? pseudoElt);
  };

  AbstractView implements ViewCSS;

  // Introduced in DOM Level 2:
  interface DocumentCSS /*: stylesheets::DocumentStyle*/ {
    CSSStyleDeclaration getOverrideStyle(in Element elt, 
                                         in DOMString? pseudoElt);
  };

  Document implements DocumentCSS;

  // Introduced in DOM   Level 2:
  interface DOMImplementationCSS /*: DOMImplementation*/ {
    CSSStyleSheet      createCSSStyleSheet(in DOMString title, 
                                           in DOMString media)
                                        raises(DOMException);
  };

  DOMImplementation implements DOMImplementationCSS;
};
